baseURL: 'https://www.extra-ransom.net/'
languageCode: en-us
title: super-chainsaw
theme: hugo-book
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
sectionPagesMenu: main

menu:
  main: 
    - identifier: projects
      name: projects 
      url: /projects/
      weight: 50
  after:
    - name: Github
      url: 'https://github.com/tommyorndorff/extra-ransom'
      weight: 10
params:
  BookTheme: auto
  BookRepo: 'https://github.com/tommyorndorff/extra-ransom'

deployment:

  targets:
    name: s3-extra-ransom
    cloudFrontDistributionID: E2498U24MEPPED
    URL: "s3://www.extra-ransom.net?region=us-east-1"
    matchers:
      - pattern: "^.+\\.(html|xml|json)$"
        gzip: true
      - pattern: "^.+\\.(js|css|svg|ttf)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: true
      - pattern: "^.+\\.(png|jpg)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: false
