baseURL: 'https://www.extra-ransom.net/'
locale: en-us
title: extra-ransom, super-chainsaw

module:
  imports:
    - path: github.com/imfing/hextra

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
  highlight:
    noClasses: false

menu:
  main:
    - name: Rod Builds
      url: /docs/rod-builds/
      weight: 10
    - name: Woodworking
      url: /docs/woodworking/
      weight: 20
    - name: Coffee Roasting
      url: /docs/coffee-roasting/
      weight: 30
    - name: GitHub
      url: https://github.com/tommyorndorff/extra-ransom
      weight: 40
      params:
        type: icon
        icon: github

params:
  navbar:
    displayTitle: true
    displayLogo: false
  sidebar:
    width: 320
  page:
    width: normal
  theme:
    default: system
    displayToggle: true
  editURL:
    enable: true
    base: https://github.com/tommyorndorff/extra-ransom/edit/main/

deployment:
  targets:
    name: s3-extra-ransom
    cloudFrontDistributionID: E2498U24MEPPED
    URL: "s3://www.extra-ransom.net?region=us-east-1"
    matchers:
      - pattern: "^.+\\.(html|xml|json)$"
        gzip: true
      - pattern: "^.+\\.(js|css|svg|ttf)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: true
      - pattern: "^.+\\.(png|jpg)$"
        cacheControl: "max-age=31536000, no-transform, public"
        gzip: false
