name: Deploy Blog

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-gatsby-tommyorndorff-site-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-tommyorndorff-site-build-
      - name: Install dependencies
        run: npm install
      - name: install gatsby cli
        run: npm install -g gatsby-cli@4.6.1
      - name: Build
        run: gatsby build
      - name: verify build
        run: ls -la public
      - name: set aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: sync to s3 bucket
        run: |
          aws s3 sync ./public/ s3://www.extra-ransom.net/ --delete
      - name: invalidate cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id E2498U24MEPPED --paths "/"